# alembic/script.py.mako
"""add username field to users table

Revision ID: f4898f31a506
Revises: '956d27e55f29'
Create Date: 2025-07-12 06:49:27.409388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4898f31a506"
down_revision: Union[str, None] = "956d27e55f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # まずnullableでカラムを追加
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))

    # 既存ユーザーにデフォルト値を設定（emailからusernameを生成）
    op.execute("""
        UPDATE users 
        SET username = COALESCE(
            split_part(email, '@', 1), 
            'user_' || id::text
        )
        WHERE username IS NULL
    """)

    # NOT NULL制約を追加
    op.alter_column("users", "username", nullable=False)

    # ユニークインデックスを作成
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
