"""merge 300ab7334998 and 20250908001

Revision ID: merge_300ab7334998_20250908001
Revises: 300ab7334998, 20250908001
Create Date: 2025-09-09 00:00:00.000000

This is an autogenerated empty merge revision to unify multiple heads.
"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "merge_300ab7334998_20250908001"
down_revision = ("300ab7334998", "20250908001")
branch_labels = None
depends_on = None


def upgrade() -> None:
    """No-op merge revision: resolves multiple heads."""
    pass


def downgrade() -> None:
    """No-op downgrade for merge revision."""
    pass
